[versions]
agp = "8.2.2"
kotlin = "1.9.22"
composeBom = "2024.09.00"
composeCompiler = "1.5.9"
activity = "1.8.2"
core = "1.12.0"
kyantShapes = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-material-ripple = { group = "androidx.compose.material", name = "material-ripple" }
kyant-shapes = { group = "io.github.kyant0", name = "shapes", version.ref = "kyantShapes" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
